version: '2.0' # specify docker-compose version

# Define the services/containers to be run
services:
  material-charts-client: # name of the first service
    build: material-charts-client # specify the directory of the Dockerfile
    ports:
      - "4210:4210" # specify port forewarding

  material-charts-server: #name of the second service
    build: material-charts-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - material-charts-db # link this service to the database service

  material-charts-db: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
    command: "--smallfiles --logpath=/dev/null"

  mongo-importer:
        build: .